Get bin/setup to die if yarn fails

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -3,6 +3,8 @@ set -e
 set -o pipefail
 set -u
 
+die() { echo "$*" 1>&2 ; exit 1; }
+
 if [[ $* == *--reset* ]];
 then
     echo "== Deleting existing node_modules =="
@@ -12,10 +14,10 @@ fi
 
 
 echo "== Installing dependencies for cultureamp-style-guide NPM package =="
-yarn install
+yarn install || die "Failed to run yarn install"
 yarn link
 
 echo "== Installing dependencies for cultureamp-style-guide/guide gatsby site =="
 cd guide
-yarn install
+yarn install || die "Failed to run yarn install on the guide"
 yarn link cultureamp-style-guide
